### ISSUE TITLE
Wrong Season Poster Being Imported

### ISSUE THREAD

**Issue by heymoe** [gboudreau/XBMCnfoTVImporter.bundle#84] opened 2016-11-26 02:50 UTC
Hey, I'm running the current build (V 1.1-67) and just did a fresh import of my library on a new server and noticed that TV shows where I have custom season posters (seasonXX-poster.jpg) for each season of a TV show (Top Gear being an example) that instead of importing the season specific poster file into Plex that it seems to be using the poster.jpg instead which lives in the same directory as the seasonXX-poster.jpg files.

The plugin logs seem to show that the correct posters were found but it still imported poster.jpg instead:

Here is an example from the logs:
com.plexapp.agents.xbmcnfotv.log:2016-11-25 09:50:28,517 (7f531affd700) :  INFO (__init__:47) - Found season poster file /xxx/xxx/Top Gear/season21-poster.jpg
com.plexapp.agents.xbmcnfotv.log:2016-11-25 09:50:28,522 (7f531affd700) :  INFO (__init__:578) - Found season poster image at /xxx/xxx/Top Gear/season21-poster.jpg

I'm not an expert at python so I'm having a bit of a time following some of the code right now. So far the only thing that is jumping out at me that might be causing this is that on line 545 seasonFilename is being set to an empty string. Then on line 577 seasonFilename is being used in the "if" section where the season poster is being set after the checkFilePaths call but between line 545 and 577 it doesn't look like seasonFilename is being defined to anything other than the empty string in 545.

**Comment by SlrG** [comment] 2016-11-26 10:26
You are right that there is a slight problem in the code there. The line 545 is old and should be removed, as it is not necessary any more. The same goes for line 547. The seasonFilename var in line 577 should be seasonPosterFilename. But this only affects the name assigned to the poster file, not the file which was loaded itself. So I don't really think this will solve your problem. Please try these changes on your server and report if it helps or not.

**Comment by SlrG** [comment] 2016-11-27 20:37
Hmm... Which plex version are you using? The newest one 1.3.0.3059 seems to show exactly the behavior you mention. I don't know the reason yet.

**Comment by heymoe** [comment] 2016-11-28 13:17
Sorry for the delay, I'm traveling for the holiday and lost access to my home network on Saturday when I was in the middle of doing one more test with a fresh install again.

I did complete a test with my prior meta data set before starting fresh again and the results of re-scanning Top Gear after purging it from Plex (move the folder, re-scan, empty trash, clean bundles, and optimize database) was the same. The season posters were not being displayed.

I am running the latest version of Plex Server (1.3.0) so I guess they did something to break things. I wonder if maybe the new WebUI included with 1.3.0 is just displaying the default poster image instead of the season folders even though the season posters are actually correctly stored / imported in the database. Once I get home later today I'll be able to do more testing and will let you know what I find. Thanks!

**Comment by SlrG** [comment] 2016-11-28 16:29
I expect this to be the cause. After reverting to the older plex version, the season posters work as they as designed. Let's hope the plex devs find and fix the problem.

**Comment by heymoe** [comment] 2016-11-29 05:22
So I did some testing once I got home tonight. I created a test library that just has Top Gear in it. Under Plex v1.3.0 I scanned the library and got the wrong season posters. I then uninstalled v1.3.0 and installed v1.2.7 while keeping the existing data. then refreshed the WebGUI and under v1.2.7 it still showed the wrong season posters. 

I then went into the test library and clicked on the settings gear icon and selected "Refresh All" after the refresh was done I refreshed the browser and now have the correct season posters.

I then un-install v1.2.7 and re-installed v1.3.0, refrshed and under v1.3.0 it still shows the correct season posters. Upon doing the "Refresh All" option again while under v1.3.0, the wrong season posters showed back up after the refresh. 

So it seems that how the data is getting imported / refreshed is somehow different between v1.2.7 and v1.3.0 as in the XBMC TV NFO agent is doing the same thing but v1.3.0 isn't handling the request the same as v1.2.7 and is actually importing the wrong info into the database since a v1.3.0 imported database is broken when using v1.2.7 also.

**Comment by SlrG** [comment] 2016-11-29 21:03
Thank you very much for your extensive testing. At the moment I see nothing I could change in the agents, that could improve this behavior. Could you check what does happen using plex' tvdb agent? Does this give trouble with the season posters, too? If not, I could check if anything has changed how they handle them.

**Comment by dwhagar** [comment] 2016-11-29 21:06
It does not, the tvdb seems to operate as it should.
---
David Wade Hagar
david.hagar@gmail.com
http://home.blazingumbra.com/cyclops.html

The freedom of expression protects you from governmental prosecution for something you've said.  It does not, nor has it ever, protected you from potentially harmful reactions of friends, neighbors, or employers, because you've said something stupid.  Doing so would infringe on their freedom of expression.

**Comment by heymoe** [comment] 2016-11-29 22:50
Indeed, creating a new library with Top Gear under both v1.2.7 and v1.3.0 using the TVDb agent results in the correct season posters being imported / displayed.

**Comment by SlrG** [comment] 2016-11-30 21:26
Thats really odd, because checking the the source of the TheTVDB plugin it does:
metadata.seasons[season_num].posters[banner_name] = 
which is basically the same as in the XBMCnfoTVImporter Agent:
metadata.seasons[season_num].posters[seasonPosterName] =

**Comment by heymoe** [comment] 2016-12-01 05:01
Very odd indeed. I did one more round of testing to make sure I was using the updates to the script noted above since I don't think I had them in place the last time I did my testing and ended up with the same results. 

I did pull a copy of the TVDb script from both v1.2.7 and v1.3.0 and there are differences between the two versions but I can't tell if the changes from v1.2.7 to v1.3.0 fixed / worked around this issue somehow.

**Comment by heymoe** [comment] 2016-12-07 13:44
Looks like v1.3.1 is out. I haven't tried it yet to see if it fixed this issue yet though. Anyone else given it a try yet?

**Comment by heymoe** [comment] 2016-12-07 18:24
Still broken in v1.3.1

**Comment by SlrG** [comment] 2016-12-07 22:32
I did an thorough comparison of the old  v1.2.7 and newer v1.3.0 TheTVDB agents. But I'm pretty sure there is no change in there, that would make the season posters work in v.1.3.0. The code is unchanged and so I still not know the cause why the season posters work in the older and fail and the newer versions. Any ideas or help are appreciated.

**Comment by nathanleviere** [comment] 2016-12-07 23:22
I have noticed that all episode thumbs are also ignored when adding new episodes in addition to the problem with the season posters. This started happening at the same time.

**Comment by heymoe** [comment] 2016-12-09 22:28
Hmm, I don't seem to have the thumb/poster issue with the actual individual episodes. Just the season posters as far as I can tell. 

I have two servers setup right now. My primary is running v1.2.7 and a test server running v1.3.1.

I've been poking at the code and learning how all this python, plex API, etc... madness works at the same time. No luck yet on my end.

**Comment by heymoe** [comment] 2016-12-09 22:43
It looks like from a metadata directory point of view on the filesystem, the correct season poster files (image) are created under ...Contents/com.plexapp.agents.xbmcnfotv/seasons and the season number xml files (1.xml, 2.xml, etc..) look correct when I compare things side by side between my v1.27 and v1.3.1 servers. 

I'll have to dig into the sqlite3 database and see if things match up in there next.

**Comment by SlrG** [comment] 2016-12-10 00:03
Thank you very much for your extensive debugging. Please let me know if you find a solution.

**Comment by FidoFuz** [comment] 2016-12-10 03:30
Some additional info not sure if it's relevant.  When I choose to Unmatch, it loses all the info but the correct season posters appear.  I'm assuming this is from the cache as I have done this previously to update season posters I have manually changed.  i.e., unmatch, clean bundles, then match.  Except now when I unmatch the correct posters appear then clean bundles then match and the posters are back to the wrong ones.

**Comment by Dingmatt** [comment] 2016-12-10 13:28
This isn't the only 3rd party meta agent to suffer from the issue.  After looking at the logs it seems that Plex is attempting to load the metadata from the wrong path, for the time being reverting back 1.2.7 is our only option.

**Comment by SlrG** [comment] 2016-12-10 13:44
@Dingmatt:
Thank you for reporting, that other agents have the same problem. This indicates a problem the plex devs will have to fix. So for the time being we have to wait and/or revert like you suggested. :)

**Comment by heymoe** [comment] 2016-12-10 16:01
Good to hear that other agents are having the same problem. Hopefully it will get fixed soon.

As far as I can tell, all the metadata files are created correctly on the file system when comparing my v1.2.7 install and the v1.3.2 install.

In the sqlite3 database though, I've found that in the metadata_items table the entry for the season information is more or less the same BUT the entry for user_thumb_url is missing (empty value) in v1.3.2 where as under v1.2.7 it has a entry for the the season poster. 

metadata://seasons/2/posters/com.plexapp.agents.xbmcnfotv_da39a3ee5e6b4b0d3255bfef95601890afd80709

I verified the file "da39a3ee5e6b4b0d3255bfef95601890afd80709" exists on the file system. I tried to manually add the same user_thumb_url entry into the v1.3.2 database which resulted in the season poster to change from the default tv show poster to no poster so that's something but not the results I was expecting. Maybe caching or other DB entries are missing or something.

Either way, it seems that for some reason all the DB entries are not getting added while all the file system work for the metadata is working which seems to point to an issue on the Plex side and not the agent since I don't things agents themselves make changes to the sqlite3 database directly.

**Comment by heymoe** [comment] 2016-12-10 16:21
Also as a side note, the changes we mentioned earlier in this thread while trying to debug and ended not not fixing anything, you might want to update anyways.

Specifically changing line 577 from:
 
metadata.seasons[season_num].posters[seasonFilename] = Proxy.Media(seasonData)

to:

metadata.seasons[season_num].posters[**seasonPosterFilename**] = Proxy.Media(seasonData)

since seasonFilename is always an empty string. Plex uses the data in that spot to generate the hash names for the files on the file system so all season posters for all TV Shows end up named the same "da39a3ee5e6b4b0d3255bfef95601890afd80709". 

Obviously this hasn't caused any problems but might be a good idea to have unique hash names for each metadata poster item.

**Comment by SlrG** [comment] 2016-12-10 21:33
Yes I already noticed that and have a local version, where this is already fixed. But as it did not solve the problem at hand, I didn't push it to the public yet. You seem to have gotten an extensive knowledge of the agents in your research. If you have ideas how to improve things, feel free to let me know anytime or send me pull requests of your changes. I'm really grateful for your contributions on this problem. :)

**Comment by heymoe** [comment] 2016-12-12 16:08
Thanks.. Not sure about my knowledge being extensive as related to Plex agents yet but have been enjoying learning more about about how it all works since this started but in general I'm happy to help where I can. 

It looks like this issue is starting to gain attention in the Plex forums from employees since multiple 3rd party agents are reporting the same or other odd issues since v1.3.x came out.  Hopefully this will get sorted out by Plex in the next version or soon.

**Comment by heymoe** [comment] 2016-12-16 13:59
Plex Server v1.3.3 is out. Will take it for a test and report back shortly

**Comment by Dingmatt** [comment] 2016-12-16 14:06
@heymoe Just to save you a bit of time, unfortunatly it hasn't fixed the issue.

**Comment by heymoe** [comment] 2016-12-16 20:23
Indeed, it's still busted.

**Comment by mwiedemann** [comment] 2017-01-13 09:17
Any news here?
Can someone explain the bug? Maybe we can help to fix it!

**Comment by Dingmatt** [comment] 2017-01-13 10:43
@mwiedemann It's not a bug in the agent but rather in Plex itself, nothing can be done until they release a fixed version.

**Comment by shortstrawfate** [comment] 2017-01-14 22:46
I used to have to do a bit of a workaround to get the season posters coming up in the older versions anyway (around the 1.1.x releases - this is going by some notes I made at the time dated at the end of August when I rebuilt my server).

I had to enable the Local Media Assets (TV) agent and drag it above the XBMCnfoTVImporter in the agent server settings. Then it seemed to get the correct season art from the Local Media agent, which would then hand over to XBMCnfoTVImporter for the rest of the metadata. Until I set it up that way I never got the season artwork.

Since the more recent Plex updates the workaround does nothing, but I guess my point is something wasn't quite right pre-1.3 at least on my machine.

Still I suppose it's for nought if it's PMS that's the problem. :)

**Comment by billpreston420** [comment] 2017-01-15 03:30
I found that if I unclaim my server, the plugin works as intended.

**Comment by SlrG** [comment] 2017-01-22 19:07
@billpreston420:
Sorry, but even if I unclaim my server, it still doesn't work. Are you sure you get the correct season posters, when the server is unclaimed?

**Comment by Em31Et** [comment] 2017-02-01 02:27
Still no fix from Plex after 3 months.
It is very disappointed that they think it is Plugin's issue instead of Plex.

**Comment by Dingmatt** [comment] 2017-02-01 09:11
@Em31Et They don't, they've confirmed they're looking into it.

**Comment by Em31Et** [comment] 2017-02-01 16:01
@Dingmatt 
Maybe "confirmed", but they do NOTHING in these 3 months.
If you check the forum, you will saw that they just started to inspect this issue a few days ago.
Before that, they just keep to say "incompatible".

**Comment by FidoFuz** [comment] 2017-02-08 15:32
I'm not sure Plex sees this as a major issue.  For me it is fundamental to the use of the Media Server.  I spend time scraping and selecting appropriate images which is now completely pointless as Plex hoses over everything I set in place.  I am stuck on v1.2.7 and unable to upgrade until Plex fix what they broke or inform plugin developers what they need to modify to take account of the Plex change.

They keep adding bells and whistles to each new update but fail to fix the basics.

**Comment by SlrG** [comment] 2017-02-09 08:34
Oh I'm pretty sure that they don't see it as important issue at all. IMHO they are not very supportive of third party additions to their product any more. Since a long time now, the development documentation, that once was available is gone. Downloads of old versions have vanished from the website. And the responsiveness on the forums is rather lacking in general (again IMHO). As a golden exception, ChuckPa is very actively trying to help us solve this problem. So I'm still hopeful, we will get it sorted out. But don't expect a fast solution. I would bet it will take some more months.

**Comment by Dingmatt** [comment] 2017-02-14 22:11
@gboudreau @heymoe Hi everyone, 

I've found a workaround for this issue, see the forum topic below:
[https://forums.plex.tv/discussion/258570/heres-the-workaround-for-the-1-3-x-1-4-x-metadata-issue/p1?new=1](https://forums.plex.tv/discussion/258570/heres-the-workaround-for-the-1-3-x-1-4-x-metadata-issue/p1?new=1)

**Comment by M0UL** [comment] 2017-02-22 12:10
this is fixed in pms version 1.4.2.3400.  after installing just refresh all the tvshows .

**Closed** 2017-02-23 01:11 UTC

**Comment by Foenix05** [comment] 2023-12-01 17:59
Hello, I have a similar problem. I don't have images of the seasons or episodes. I am attaching some screenshots.
The Plex server is installed on Nvidia Shield.
I've been looking all afternoon for ways to solve the problem but I can't find anything, and it works for other people (Problem related to the Shield?)
Thanks in advance

![Capture d'écran 2023-12-01 185518](https://github.com/gboudreau/XBMCnfoTVImporter.bundle/assets/152645123/dd532213-e5ce-499d-ae25-e521957500a0)
![Capture d'écran 2023-12-01 185536](https://github.com/gboudreau/XBMCnfoTVImporter.bundle/assets/152645123/6b556611-cae0-4c9f-9df6-bc8e0b10c917)
![Capture d'écran 2023-12-01 185552](https://github.com/gboudreau/XBMCnfoTVImporter.bundle/assets/152645123/0a1453f5-3703-4299-a010-d435f2230eab)
![Capture d'écran 2023-12-01 185634](https://github.com/gboudreau/XBMCnfoTVImporter.bundle/assets/152645123/6c2b18c9-6522-49b6-987b-968ec312dfd5)
